[versions]
agp = "8.13.2"
activityCompose = "1.12.4"
accompanistPermissionsVersion = "0.37.3"
barcodeScanningVersion = "17.3.0"
cameraVersion = "1.5.3"
composeBom = "2026.02.00"
coreKtx = "1.17.0"
datastoreVersion = "1.2.0"
gsonVersion = "2.13.2"
kotlin = "2.3.10"
lifecycleRuntimeKtx = "2.10.0"
mpAndroidChartVersion = "v3.1.0"
navigationCompose = "2.9.7"
okhttpVersion = "5.3.2"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissionsVersion" }
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcodeScanningVersion" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraVersion" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraVersion" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraVersion" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraVersion" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVersion" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
mp-android-chart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpAndroidChartVersion" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttpVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
